### ISSUE TITLE
Basic Project Structure

### ISSUE THREAD

**Issue by spatiszisis** [Trapezokomos/dashboard#1]
On this issue I will add the following technologies
- [x] PostgreSQL
- [x] Docker with PostgreSQL
- [x] Flyway for database versioning
- [x] Basic Project structure
- [x] Prometheus & Grafana
- [x] Jenkins integration (CICD)

**Comment by EmmanSkout** [comment]
We can also consider the following technlogies :

- Prometheus & Grafana (status metrics and visualization)

- Jenkins integration (CICD)

**Comment by spatiszisis** [comment]
Issue handled on the attached PR
